title: VKVG Documentation
author: Jean-Philippe Bruyère
email: jp_bruyere@hotmail.com
twitter_username: jpbruyere
github_username: jpbruyere
description: >-
  description: Open source 2d vector graphic library for vulkan writen in c.
url: http://github.com/jpbruyere/vkvg # root address of the site

theme: no-style-please
#remote_theme: riggraz/no-style-please


addons:
  - github
  - plugins
  - analytics

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-admin
  - jekyll-datapage-generator

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
#exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
