title: VKVG Documentation
author: Jean-Philippe Bruyère
email: jp_bruyere@hotmail.com
url: http://github.com/jpbruyere/vkvg # root address of the site
description: >-
  description: Open source 2d vector graphic library for vulkan writen in c.

baseurl: "/vkvg" # the subpath of your site, e.g. /blog
url: "https://jpbruyere.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jpbruyere
github_username: jpbruyere

# Build settings
# theme: no-style-please
remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

addons:
  - github
  - plugins
  - analytics

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
